spec_version: 2-preview
description: Deploys a vm from a template on a vcenter with terraform and configures httpd server on it via ansible playbook

outputs:
  qualix_link:
    value: '{{ .grains.Centos.outputs.qualix_link }}'
    kind: link
  vsphere_virtual_machine_default_ip_address:
    value: '{{ .grains.Centos.outputs.vsphere_virtual_machine_default_ip_address }}'
  vsphere_virtual_machine_name:
    value: '{{ .grains.Centos.outputs.vsphere_virtual_machine_name }}'
  OS Login:
    value: root
  Os Password:
    value: qs1234

grains:
  Centos:
    kind: terraform
    spec:
      inputs:
        - virtual_machine_template_name: Do-Template-Centos
        - virtual_machine_name: "TorqueTestVM-{{ sandboxid }}"
        - datacenter_name: "IL Datacenter"
        - datastore_name: "vmfs02-Do-Reservation"
        # - compute_cluster_name: "IL Main Cluster\esxi-01.qualisystems.local"
        - networks: "LAB/Do.(85)"
        - wait_for_ip: 360
        - wait_for_net: 360
        - VM_username: root
        - VM_password: qs1234
        - qualix_ip: '{{ .params.default_qualix_ip }}'
        - connection_protocol: ssh
        - connection_port: 22

      outputs:
      - qualix_link
      - vsphere_virtual_machine_default_ip_address
      - vsphere_virtual_machine_name
      source:
        store: Torque-Assets
        path: terraform/vm-from-template-wait-for-ip-no-creds
      host:
        cloud-account: private-cloud
        compute-service: vcenter3

  apache_install:
    depends-on: virtual_machine
    kind: ansible
    spec: 
      source:
        path: https://github.com/QualiNext/test-spec2-public//ansible/install_httpd.yaml
      host:
        name: docker-agent
      inventory-file:
        all:
          hosts:
            vcenter_machine:
              ansible_host: '{{ .grains.Centos.outputs.vsphere_virtual_machine_default_ip_address }}'
              ansible_user: root
              ansible_password: qs1234

